image:
- Visual Studio 2017
environment:
  nodejs_version: "10"
  appveyor_build_worker_cloud: gce
  NASM_URL: http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/win64/nasm-2.12.02-installer-x64.exe
  BUILD_ARCH: win
  matrix:
    - BUILD_NODE_VERSION: 9.11.1
    - BUILD_NODE_VERSION: 8.11.1
    - BUILD_NODE_VERSION: 8.10.0
platform:
  - x64

configuration:
  - Release

branches:
  only:
    - master

matrix:
  fast_finish: true

cache:
  - '%UserProfile%\.m2'
  - tmp -> appveyor.yml
  - '%APPDATA%\npm-cache -> yarn.lock'
  - node_modules -> yarn.lock
  - '%SystemRoot%\boot.exe -> boot.properties'
  - '%UserProfile%\.boot\cache\lib -> boot.properties'
  - '%UserProfile%\.boot\cache\bin -> boot.properties'

install:
  # Install NASM
  # TODO: Remove after https://github.com/appveyor/ci/issues/1426 is fixed
  - set "PATH=C:\Program Files\Git\mingw64\bin;%PATH%"
  - curl -L -o nasminst.exe "%NASM_URL%"
  - start /wait nasminst /S
  - ps: Import-Module "C:\projects\lumo\scripts\AdjustVirtualMemoryPagingFileSize.psm1"
  - ps: Set-OSCVirtualMemory  -InitialSize 2048  -MaximumSize 4096  -DriveLetter "C:"
  - ps: Install-Product node $env:nodejs_version x64
  - cmd: npm install -g npm@latest
  - cmd: npm install -g yarn
  - set PATH=%APPDATA%\npm;%PATH%
  - cmd: yarn install
  - ps: wget 'https://github.com/boot-clj/boot-bin/releases/download/latest/boot.exe' -OutFile "$pwd\boot.exe"
  - cmd: 'move boot.exe %SystemRoot%' #set PATH=$pwd\boot.exe;%PATH%

test_script:
  - yarn lint
  - yarn type:check
  - yarn test
  - cmd: boot test
  - cmd: boot release-ci
  - cmd: scripts/test-build.bat

artifacts:
  - path: build
    name: lumo-$(BUILD_ARCH)-node-v$(BUILD_NODE_VERSION)

# Don't actually build (MSBuild).
build: off
