environment:
  nodejs_version: "7.0.0"

platform:
  - x64

configuration:
  - Release

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version x64
  - ps: npm install -g yarn
  - cmd: yarn install
  - ps: wget 'https://github.com/boot-clj/boot-bin/releases/download/latest/boot.exe' -OutFile "$pwd\boot.exe"
  - cmd: set PATH=$pwd\boot.exe;%PATH%

test_script:
  - yarn lint
  - yarn type:check
  - yarn test
  - cmd: boot test
  - cmd: boot release-ci

artifacts:
  - path: main.exe
    name: Lumo

# Don't actually build (MSBuild).
build: off
